### ISSUE TITLE
接口转换中文网址似乎不行

### ISSUE THREAD

**Issue by 99junlin99** [Fndroid/jsbox_script#12]
类似君临.我爱你等等的中文网址，即便转码似乎也是not found

**Comment by Fndroid** [comment]
@99junlin99 URL编码

**Comment by 99junlin99** [comment]
我现在感觉是gogs的问题了。。。。。。但是我直接打开网址没得问题，surge用这个网址托管也没得问题，哭泣

**Comment by Fndroid** [comment]
能试一下编码？

**Comment by 99junlin99** [comment]
我试了。。。转换成英文和unicode都试过

**Comment by Fndroid** [comment]
@99junlin99 https://www.google.com/amp/s/amp.urlencoder.org/

**Comment by 99junlin99** [comment]
我还是手动改吧。。。我用你网址也试了试，不得行。。也有可能服务器的问题，我自己搭建的gogs
