### ISSUE TITLE
Picsew Tool好像用不了

### ISSUE THREAD

**Issue by Hatsune39** [Fndroid/jsbox_script#14]
用的是1.43.0目前最新的JSBox，最近长截图和图片带壳都没反应

**Comment by Fndroid** [comment]
@Hatsune39 试了一下没有问题，picsew是最新么

**Comment by Hatsune39** [comment]
@Fndroid 是扫这个二维码下载的 
<img width="526" alt="屏幕快照 2019-03-31 下午10 13 05" src="https://user-images.githubusercontent.com/20898148/55290167-348f8700-5402-11e9-9c44-0185740d6a92.png">

运行起来的效果
http://i1.bvimg.com/682331/61adbad6145f6cda.gif

**Comment by Fndroid** [comment]
你是不是没有安装Picesw这个APP

**Comment by Hatsune39** [comment]
@Fndroid  ∑(￣□￣;)原来是配合Picesw这个app使用的啊，我以为是在jsbox里实现的，明白了
