### ISSUE TITLE
V2RayN转换Quantumult请教

### ISSUE THREAD

**Issue by FenghenHome** [Fndroid/jsbox_script#15]
HI Fndroid您好！

let obfs = `,obfs=${jsonConf.net === 'ws' ? 'ws' : 'http'},obfs-path="${jsonConf.path || '/'}",obfs-header="Host:${jsonConf.host || jsonConf.add}[Rr][Nn]User-Agent:${ua}"`
let quanVmess = `${jsonConf.ps} = vmess,${jsonConf.add},${jsonConf.port},${method},"${jsonConf.id}",group=${group},over-tls=${jsonConf.tls === 'tls' ? 'true' : 'false'},certificate=1${jsonConf.type === 'none' && jsonConf.net !== 'ws' ? '' : obfs}`

jsonConf.type === 'none' && jsonConf.net !== 'ws' ? '' : obfs
伪装类型为none的h2和ws，只有ws才有混淆

{jsonConf.net === 'ws' ? 'ws' : 'http'
以上的http对应的是什么协议，不是h2的http协议吗

**Comment by Fndroid** [comment]
没懂你要表达什么，是我写错了？

**Comment by FenghenHome** [comment]
请教一下以上的http对应v2ray中那个协议，感谢

**Comment by Fndroid** [comment]
@FenghenHome tcp

**Comment by FenghenHome** [comment]
谢谢解答，最后一个请教

vmess://WS+TLS订阅B=vmess, www.bb.com, 443, chacha20-ietf-poly1305, "362c1a5b-5042-4625-9258-a91ec0bebbbc", group=节点组B, over-tls=true, tls-host=www.bb.com, certificate=1, obfs=ws, obfs-path="/path", obfs-header="Host: www.bb.com[Rr][Nn]User-Agent: safari/5.1
以上是圈的订阅格式，可是你的转换脚本中为何缺少tls-host

**Comment by Fndroid** [comment]
@FenghenHome v2rayn并没有这个字段

**Comment by FenghenHome** [comment]
tls-host是否可以直接等于jsonConf.add

**Comment by Fndroid** [comment]
@FenghenHome 不能

**Comment by xiaoshyang** [comment]
v2rayN2quan 这现在提示404，自己怎么搭建这个服务，可以给个步骤吗？

**Comment by Fndroid** [comment]
> v2rayN2quan 这现在提示404，自己怎么搭建这个服务，可以给个步骤吗？

没有步骤
