### ISSUE TITLE
QuantumultNoFA 不支持策略

### ISSUE THREAD

**Issue by 1oe** [Fndroid/jsbox_script#16]
‘’’ js
    reg: { text: "选择Apple的Policy，不懂就选择DIRECT" },
    rep: { text: "🍎 Apple" }
‘’’

**Comment by Fndroid** [comment]
@1oe 现在已经不需要这个了吧

**Comment by Fndroid** [comment]
@1oe Quantumult已经会记住之前的选择了

**Comment by 1oe** [comment]
@Fndroid  我是直接修改配置文件，你不打算做这个吗？

**Comment by Fndroid** [comment]
@1oe 这个是因为以前不会记住选择的内容才需要的，现在它会记住了你可以直接用app里面的更新了

**Comment by 1oe** [comment]
@Fndroid 怎么增加策略

**Comment by 1oe** [comment]
@Fndroid 
把默认的PROXY统统改为“🍃 Proxy”，可以这么写：
,(?:PROXY|Proxy) = ,🍃 Proxy

这样配置没用

    reg: { text: ",\s*(?:PROXY|Proxy)" },
    rep: { text: ",🍃 PROXY" }

**Comment by 1oe** [comment]
@Fndroid 

- 使用 QuantumultNoFA 更新规则后

- 在 ~Filter~ 里看到的是 Proxy

- 我已经设置好了策略

**Comment by Fndroid** [comment]
@1oe 我的意思是现在不需要这个脚本了

**Comment by 1oe** [comment]
@Fndroid QuantumultNoFA 可以同时更新 ‘Filter’ 和 ‘url’ , 能不能更新一下
