### ISSUE TITLE
规则openapi - reject求解

### ISSUE THREAD

**Issue by brydio** [Fndroid/jsbox_script#17]
访问有道翻译的openapi的时候被Rewrite reject了

**Comment by Fndroid** [comment]
> 访问有道翻译的openapi的时候被Rewrite reject了

这是规则问题，要到规则的repo里提 lhie1/Rules

**Comment by brydio** [comment]
> > 访问有道翻译的openapi的时候被Rewrite reject了
> 
> 这是规则问题，要到规则的repo里提 lhie1/Rules


好的，已经提过去了
