### ISSUE TITLE
It seems that the template literals is not supported by jsbox now.

### ISSUE THREAD

**Issue by labixiaoshuai** [Fndroid/jsbox_script#4]
https://github.com/Fndroid/jsbox_script/blob/aca577f58e9055d9a7642cbf1f4d96df9f974002/ss2surge.js#L35

**Comment by labixiaoshuai** [comment]
**It's my mistake,template literals is supported.I found another problem,after i download and run the script first time,it shows an error.Maybe there should be** `catch (err)`

![photo_2018-05-17_15-47-26](https://user-images.githubusercontent.com/35826995/40163529-9d863df8-59e9-11e8-9599-fb339ca37fe4.jpg)

**Comment by Fndroid** [comment]
fixed
